### ISSUE TITLE
Problem regarding slicing of the object

### ISSUE THREAD

**Issue by vrajesium** [epit3d/spycer#11]
Hi, I'm Vrajesh. I am working on a project where this software would be very helpful. I did as you directed for the software to run in Ubuntu 18.04  but got some issues. I have mechanical engineering background so doesn't know much about the advanced stuff. 
Image of the problem are attached below.
![1](https://user-images.githubusercontent.com/68181488/87306501-ba6f0d00-c535-11ea-8f0d-1006bfae1036.PNG)
The Folder
![2](https://user-images.githubusercontent.com/68181488/87306572-d5da1800-c535-11ea-81c8-b5bd3aa52cd5.PNG)

Hoping for your help

**Comment by l1va** [comment]
Hi, first you need to build goosli project and put binaries (result files), not source code. 
(ps. Good description with pictures - it was easy to understand your problem, thanks)
![image](https://user-images.githubusercontent.com/1406586/87308611-23e62000-c524-11ea-809d-9dc4ccecce37.png)

**Comment by vrajesium** [comment]
can you help me build the binaries from the source code? any process, command or tool to create binaries.
thank you.

**Comment by l1va** [comment]
install golang and just do what is in the readme of the goosli. And then copy binaries from $home$/go/bin folder (or your path)
![image](https://user-images.githubusercontent.com/1406586/87314682-44b27380-c52c-11ea-893d-e9003e2643aa.png)

**Comment by vrajesium** [comment]
This is what i get everytime. I have tried it before.
![3](https://user-images.githubusercontent.com/68181488/87315842-8bab6380-c542-11ea-9bb6-e78871b66e1d.PNG)

**Comment by l1va** [comment]
https://stackoverflow.com/questions/13214029/go-build-cannot-find-package-even-though-gopath-is-set

**Comment by vrajesium** [comment]
That was of no help to me. I tried it but it didn't worked out, if you could send me all those binaries for ubuntu in zip.

**Comment by vrajesium** [comment]
The problem with binaries is solved,
![Spycer Folder](https://user-images.githubusercontent.com/68181488/88894157-17243480-d265-11ea-88f2-196a147374cb.png)

But when i run  the main.py it doesnt work & shows the black screen.
![Main py ](https://user-images.githubusercontent.com/68181488/88894270-3f139800-d265-11ea-992d-28d650aa9138.png)

Also got problem with PyVTK.
![PyVTK](https://user-images.githubusercontent.com/68181488/88894421-7aae6200-d265-11ea-875d-cff866ec4f56.png)

**Comment by l1va** [comment]
Have not tried Ubuntu 20. But seems should be the same...
