### ISSUE TITLE
Sir... please help me. No matter what I try, I get an error...

### ISSUE THREAD

**Issue by kwon-wonbai** [epit3d/spycer#72]
I  make 'lib' directory  to ' C:\Users\USER\spycer-master\spycer-master' . and  in it,  placed  'planes_file.txt'  and  goosli bin  file  and data directory of goosli folder....

and then   clicked  '5D  generator  button'   but   i  get  error....

 start slicing
Error: (<class 'subprocess.CalledProcessError'>, CalledProcessError(1, ['./lib/goosli', '--cmd=slice', '--settings=settings.yaml']), <traceback object at 0x0000016D33C28680>)
Error2: b"2023/05/04 23:22:55 yamlFile.Get err: open data/config.yaml: The system cannot find the path specified. \ngoosli: error: unknown long flag '--cmd', try --help\n"

what is  this.... what can  i do ...... help me  ser............please.........plese....

**Comment by lvjonok** [comment]
Hello! We have stopped support of `goosli` slicer with `spycer`. To use it with latest `goosli` you may try to downgrade `spycer` branch to about Oct 24, 2020.

Master branch of this repository is mostly for acquaintance with our possibilities.

**Comment by kwon-wonbai** [comment]
Thank you for your kind reply.

**Comment by kwon-wonbai** [comment]
As you told me, I ran the spycer version with the 2020-10-24 version. It works. But one problem arose. If  I open the goosli-out.gcode file created by clicking the 'vip slicing' button,  X, Y, Z values ​​appear, but A-axis and B-axis values ​​do not appear. You must be busy, but your help would be greatly appreciated.

For reference, my compiler debug window shows the following message:

C:\Users\USER\Go\src\github.com\l1va\goosli\slicers\test_models\odnzak.stl
['./goosli', '--stl=C:/Users/USER/Go/src/github.com/l1va/goosli/slicers/test_models/odnzak.stl', '--gcode=goosli_out.gcode', '--layer_height=0.2', '--originx=-32.50090503692627', '--originy=0.03284502029418945', '--originz=-0.0', '--rotcx=0', '--rotcy=0', '--rotcz=50', '--wall_thickness=0.8', '--fill_density=20', '--bed_temperature=60', '--extruder_temperature=200', '--print_speed=50', '--line_width=0.4', '--slicing_type=vip', '--planes_file=planes_file.txt', '--print_speed_layer1=50', '--print_speed_wall=50', '--filling_type=Lines', '--angle=30', '--retraction_speed=0', '--retraction_distance=0', '--support_offset=1.0', '--skirt_line_count=3']
cut mesh, init and joined 68 2
A OR B ZERO 0.000 0.000 0.475 3.705 4.181
A OR B ZERO 0.000 0.000 1.363 3.922 5.285
A OR B ZERO 0.000 0.000 0.831 4.454 5.285
A OR B ZERO 0.000 0.000 1.167 3.761 4.928
A OR B ZERO 0.000 0.000 0.453 4.727 5.180
A OR B ZERO 0.000 0.000 0.432 4.747 5.179
A OR B ZERO 0.000 0.000 0.065 5.077 5.142
not closed  0.000
A OR B ZERO 0.000 0.000 2.030 3.401 5.431
not closed  0.000
.......
not closed  0.303
not closed  2.537
A OR B ZERO 0.000 0.000 2.873 0.000 2.839
not closed  2.537
not closed  4.771
A OR B ZERO 0.000 0.000 1.788 0.000 1.819
not closed  4.771
not closed  6.821
not closed  6.821
MORE 5 2.195 2.195
not closed  8.009
.......
not closed  10.226
not closed  10.226
A OR B ZERO 0.000 0.000 0.443 5.009 5.451
not closed  10.847
not closed  10.847
not closed  11.468
....
not closed  13.950
not closed  14.373
not closed  14.373
A OR B ZERO 0.000 0.000 0.581 2.969 3.550
not closed  14.795
not closed  14.795
not closed  15.218
.........
not closed  16.302
not closed  16.562
not closed  16.562
A OR B ZERO 0.000 0.000 0.570 4.580 5.150
not closed  16.821
not closed  16.821
not closed  17.081
not closed  17.081
not closed  17.340
A OR B ZERO 0.000 0.000 0.548 4.601 5.148
not closed  17.340
not closed  17.599
........
not closed  18.118
not closed  18.378
....
......
not closed  19.506
not closed  19.553
not closed  19.553
A OR B ZERO 0.000 0.000 3.759 1.406 5.166
not closed  19.600
not closed  19.600
not closed  19.648
not closed  5.443
not closed  5.443
not closed  3.349
not closed  3.349
MORE 5 2.113 1.315
MORE 5 2.533 2.533

.......

MORE 5 2.533 2.533
MORE 5 2.533 2.533
A OR B ZERO 0.000 0.028 0.289 0.411 0.000
A OR B ZERO 0.000 0.000 4.423 0.834 5.257
......

A OR B ZERO 0.000 0.000 0.154 5.161 5.315
A OR B ZERO 0.000 0.000 0.000 5.285 5.285
MORE 5 2.089 2.089
......

MORE 5 2.481 2.481
MORE 5 6.538 5.454
MORE 5 10.014 10.014
A OR B ZERO 0.000 0.840 2.110 2.801 0.000
