### ISSUE TITLE
Spycer Language Problem!

### ISSUE THREAD

**Issue by beshoyr100** [epit3d/spycer#95]
in the pictures 'spycer' was shown in English but when I built, it was in Ukrainian I think, How can I change it in English? I couldn't figure that out.

![Screenshot 2023-07-20 005308](https://github.com/epit3d/spycer/assets/40214742/56aadc5e-8399-4466-b440-54a92ee26524)

**Comment by lvjonok** [comment]
Hello @beshoyr100! Thank you for your interest in our software!

Currently we do not publish current version of slicer software, so you cannot really try out 5D slicing, just look at our interface. If you want to try latest public version of our slicer you should downgrade `spycer` to commit about Oct 24, 2020.

In case you are intersected in just GUI and want English, this [line](https://github.com/epit3d/spycer/blob/1c51f376d58482310c3fe83acafdaed823d97542/settings.yaml#L14) changes language settings. You can simply replace it with `en`.
